namespace Cifs.Res
{
    using System;
	using System.Collections.Specialized;

    /// <summary>
    ///    This class contains name-value pairs
    /// </summary>
    public sealed class Resources
    {
        internal NameValueCollection fContent = new NameValueCollection();

		internal Resources()
		{
			// Communication errors
			fContent.Add("CM1"             , "Host unknown: {0}");
			fContent.Add("CM2"             , "Cannot connect to server: {0}");
			fContent.Add("CM3"             , "Cannot resolve NetBIOS name {0}");


			// NetBIOS negativ response errors

			fContent.Add("NB128"           , "Not listining called name");         // NR_EC_NOT_LISTINING_CALLED_NAME
			fContent.Add("NB129"           , "Not listining calling name");         // NR_EC_NOT_LISTINING_CALLING_NAME
			fContent.Add("NB130"           , "Called name not present");            // NR_EC_CALLED_NAME_NOT_PRESENT
			fContent.Add("NB131"           , "Insufficient resources");             // NR_EC_INSUFFICIENT_RESOURCES
			fContent.Add("NB143"           , "Unspecified NetBIOS response error"); // NR_EC_UNSPECIFIED_ERROR
			fContent.Add("NB9999"          , "NetBIOS negative response {0}");

			// Own NetBIOS errors
			fContent.Add("NB500"           , "NetBIOS write failure");
			fContent.Add("NB501"           , "NetBIOS read failure");
			fContent.Add("NB502"           , "Retarget response not yes implemented");
			fContent.Add("NB503"           , "Invalid NetBIOS response type: {0}");
			fContent.Add("NB504"           , "NetBIOS session is closed");



			// Name
			fContent.Add("MN1"             , "Invalid UNC or URL name syntax: {0}");
			fContent.Add("WWW1"             , "Cannot read from CifsURLConnection if doInput=false - call setDoInput(true)");
			fContent.Add("WWW2"             , "Cannot write to a CifsURLConnection if doOutput=false - call setDoOutput(true)");
			fContent.Add("WWW3"             , "Cannot write output after reading input");




			/*------------------------ SMB error codes -----------------------*/

			fContent.Add("U:U"             , "Unexpected SMB error code.");
			// DOS errors
			fContent.Add("1:1"             , "Invalid function.  The server did not recognize or could not perform a system call generated by the server");
			fContent.Add("1:2"             , "File not found");
			fContent.Add("1:3"             , "Directory invalid");
			fContent.Add("1:4"             , "Too many open files.  The server has no file handles available.");
			fContent.Add("1:5"             , "Access denied, the client's context does not permit the requested function.");
			fContent.Add("1:6"             , "Invalid file handle.  The file handle specified was not recognized by the server.");
			fContent.Add("1:7"             , "Memory control blocks destroyed.");
			fContent.Add("1:8"             , "Insufficient server memory to perform the requested function.");
			fContent.Add("1:9"             , "Invalid memory block address.");
			fContent.Add("1:10"            , "Invalid environment.");
			fContent.Add("1:11"            , "Invalid format.");
			fContent.Add("1:12"            , "Invalid open mode.");
			fContent.Add("1:13"            , "Invalid data ");
			fContent.Add("1:15"            , "Invalid drive specified.");
			fContent.Add("1:16"            , "A Delete Directory request attempted to remove the server's current directory.");
			fContent.Add("1:17"            , "Not same device");
			fContent.Add("1:18"            , "A File Search command can find no more files matching the specified criteria.");
			fContent.Add("1:32"            , "The sharing mode specified for an Open conflicts with existing FIDs on the file.");
			fContent.Add("1:33"            , "A Lock request conflicted with an existing lock or specified an invalid mode");
			fContent.Add("1:50"            , "Operation not supported on this server");
			fContent.Add("1:80"            , "The file named in a Create Directory, Make New File or Link request already exists.");
			fContent.Add("1:230"           , "Pipe invalid.");
			fContent.Add("1:231"           , "All instances of the requested pipe are busy.");
			fContent.Add("1:232"           , "Pipe close in progress.");
			fContent.Add("1:233"           , "No process on other end of pipe.");
			fContent.Add("1:234"           , "There is more data to be returned.");
			fContent.Add("1:267"           , "Invalid directory name in a path");
			// SRV errors
			fContent.Add("2:1"             , "Non-specific error code.");
			fContent.Add("2:2"             , "Bad password");
			fContent.Add("2:4"             , "The client does not have the necessary access rights within the specified context");
			fContent.Add("2:5"             , "The Tid specified in a command was invalid.");
			fContent.Add("2:6"             , "Invalid network name in tree connect.");
			fContent.Add("2:7"             , "Invalid device - printer request made to non-printer connection or non-printer request made to printer connection.");

			fContent.Add("2:49"            , "Print queue full (files) -- returned by open print file.");
			fContent.Add("2:50"            , "Print queue full -- no space.");
			fContent.Add("2:51"            , "EOF on print queue dump.");
			fContent.Add("2:52"            , "Invalid print file FID.");
			fContent.Add("2:64"            , "The server did not recognize the command received.");
			fContent.Add("2:65"            , "The server encountered an internal error, e.g., system file unavailable.");
			fContent.Add("2:67"            , "The Fid and pathname parameters contained an invalid combination of values.");
			fContent.Add("2:69"            , "The access permissions specified for a file or directory are not a valid combination.");
			fContent.Add("2:71"            , "The attribute mode in the Set File Attribute request is invalid.");
			fContent.Add("2:81"            , "Server is paused.  (reserved for messaging)");
			fContent.Add("2:82"            , "Not receiving messages.  (reserved for messaging).");
			fContent.Add("2:83"            , "No room to buffer message.  (reserved for messaging).");
			fContent.Add("2:87"            , "Too many remote user names.  (reserved for messaging).");
			fContent.Add("2:88"            , "Operation timed out.");
			fContent.Add("2:89"            , "No resources currently available for request.");
			fContent.Add("2:90"            , "Too many Uids active on this session.");
			fContent.Add("2:91"            , "The Uid is not known as a valid user identifier on this session.");
			fContent.Add("2:250"           , "Temporarily unable to support Raw, use MPX mode.");
			fContent.Add("2:251"           , "Temporarily unable to support Raw, use standard read/write.");
			fContent.Add("2:252"           , "Continue in MPX mode.");
			fContent.Add("2:65535"         , "Function not supported.");

			// HW  errors
			fContent.Add("3:19"            , "Attempt to write on write-protected media");
			fContent.Add("3:20"            , "Unknown unit.");
			fContent.Add("3:21"            , "Drive not ready.");
			fContent.Add("3:22"            , "Unknown command.");
			fContent.Add("3:23"            , "Data error (CRC).");
			fContent.Add("3:24"            , "Bad request structure length.");
			fContent.Add("3:25"            , "Seek error.");
			fContent.Add("3:26"            , "Unknown media type.");
			fContent.Add("3:27"            , "Sector not found.");
			fContent.Add("3:28"            , "Printer out of paper.");
			fContent.Add("3:29"            , "Write fault.");
			fContent.Add("3:30"            , "Read fault.");
			fContent.Add("3:31"            , "General failure.");
			fContent.Add("3:32"            , "A open conflicts with an existing open.");
			fContent.Add("3:33"            , "A Lock request conflicted with an existing lock or specified an invalid mode,");
			fContent.Add("3:34"            , "The wrong disk was found in a drive.");
			fContent.Add("3:35"            , "No FCBs are available to process request.");
			fContent.Add("3:36"            , "A sharing buffer has been exceeded.");

			// CMD error
			fContent.Add("255:0"           , "Command was not in the SMB format");


			// Protocol error
			fContent.Add("PE1"             , "Server does support requested protocols");
			fContent.Add("PE2"             , "Only NT LM 0.12 protocol implemented. {0} not supported");
			fContent.Add("PE3"             , "Invalid server response");


			// Session
			fContent.Add("SS1"             , "Session {0} already exists");
			fContent.Add("SS2"             , "Session {0} does not exist");

			// CifsFile*Stream
			fContent.Add("FS0"             , "Resetting to invalid mark");
			fContent.Add("FS1"             , "File is closed");
			fContent.Add("FS2"             , "Mode must be r or rw");



			// RemoteAdmin

			fContent.Add("RA2"             , "RemoteAdmin {0} does not exist");

			// Disk

			fContent.Add("DK2"             , "Disk {0} does not exist");
			fContent.Add("DK3"             , "Invalid disk name syntax: {0} ");
			fContent.Add("DK4"             , "File/Directory  {0} already exists");
			fContent.Add("DK5"             , "File {0} does not exist");
			fContent.Add("DK6"             , "Directory {0} does not exist");

			// LM Error codes
			fContent.Add("LM5"             , "User has unsufficient privilege");
			fContent.Add("LM50"            , "The network request is not supported");

			fContent.Add("LM65"            , "Network access is denied");
			fContent.Add("LM86"            , "Invalid password");
			fContent.Add("LM2103"          , "The server could not be located");
			fContent.Add("LM2114"          , "The server service on the remote computer is not running");
			fContent.Add("LM2141"          , "IPC$ is not shared");
			fContent.Add("LM2150"          , "The specified queue name is invalid");
			fContent.Add("LM2151"          , "The specified print jon could not be located");
			fContent.Add("LM2160"          , "The print process is not responding");
			fContent.Add("LM2161"          , "The spooler is not started on the remote server");
			fContent.Add("LM2164"          , "Operation cannot be performed on the job");
			fContent.Add("LM2123"          , "Buffer was too small");
			fContent.Add("LM2221"          , "The user name was not found");
			fContent.Add("LM2243"          , "The password cannot be changed");
			fContent.Add("LM2246"          , "The password ist too short");


			fContent.Add("LMERROR"         , "Server error ({0})");
		
		}

		public NameValueCollection getContents()
		{
			return fContent;
		}

		public string getString(string key)
		{
			return fContent.Get(key);
		}

		public string this[string Key]
		{
			get
			{
				string r = fContent.Get(Key);
				if (r == null)
					r = "Unspecified Error";
					//throw new ArgumentException("Key not found.", "Key");
				return r;
			}
			set
			{
				fContent.Add(Key, value);
			}
		}

	

    } // class Resources
} // namespace Cifs.Res